### ISSUE TITLE
Java Patterns

### ISSUE THREAD

**Issue by riteshhon** [vaibhavnirmal2001/DSA-hacktoberfest#33]
Hey @vaibhavnirmal2001,
I am having more java patterns to add it in the java patterns folder. Please assign me this issue so that I will add more pattern code in the Java Pattern folder.

Thanks!

**Comment by vaibhavnirmal2001** [comment]
sure!

**Comment by riteshhon** [comment]
Hey @vaibhavnirmal2001,
Please check the PR. Also, Once it gets approved from your end. I will add more java patterns.

Thanks!

**Comment by vaibhavnirmal2001** [comment]
appreoved
